# Generated by Django 4.2.16 on 2024-12-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_video_description_and_more'),
        ('category', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='category', to='video.video'),
        ),
    ]
