# Generated by Django 4.2.16 on 2024-12-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='video',
        ),
    ]
