name: vn-backend
dependencies:
    - python=3.8.20
    - pip=24.2
    - pip:
        - django==4.2.16
        - psycopg2-binary==2.9.10
        - django-dotenv==1.4.2
        - djangorestframework==3.15.2
        - drf-yasg==1.21.8
        - clerk_backend_api==1.4.1

