name: vn-backend
dependencies:
    - python=3.12.3
    - pip=24.2
    - pip:
        - django==4.2.16
        - psycopg2-binary==2.9.10
        - django-dotenv==1.4.2
        - djangorestframework==3.15.2
        - drf-yasg==1.21.8
        - django-cors-headers==4.4.0
        - gunicorn==23.0.0
        - dj-database-url==2.3.0
        - whitenoise==6.7.0
        - djangorestframework_simplejwt==5.3.1
        - django-extensions==3.2.3
        - django-fullurl==1.4


