# Generated by Django 4.2.16 on 2024-12-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='external_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
