# Generated by Django 4.2.16 on 2024-12-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_host_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_host_thumbnail_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_host_url',
            field=models.CharField(max_length=200),
        ),
    ]
