# Generated by Django 4.2.16 on 2024-12-04 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_userprofile_is_following'),
        ('video', '0004_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='user_profile.userprofile'),
            preserve_default=False,
        ),
    ]
