# Generated by Django 4.2.16 on 2024-12-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_timestamp',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
