# Generated by Django 4.2.16 on 2024-12-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_tag_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='video',
        ),
    ]
