# Generated by Django 4.2.16 on 2024-12-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0003_alter_userprofile_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=100)),
                ('space_description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='user_profile.userprofile')),
            ],
        ),
    ]
