# Generated by Django 4.2.16 on 2024-12-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_space_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='space_owner',
        ),
    ]
