# Generated by Django 4.2.16 on 2024-12-17 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_userprofile_is_following'),
        ('space', '0003_remove_space_space_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='space_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='user_profile.userprofile'),
            preserve_default=False,
        ),
    ]
